# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import directorselection_pb2 as directorselection__pb2


class GetInformationAboutDirectoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DirectoryCall = channel.unary_unary(
                '/directorselection.GetInformationAboutDirectory/DirectoryCall',
                request_serializer=directorselection__pb2.Request.SerializeToString,
                response_deserializer=directorselection__pb2.Reply.FromString,
                )


class GetInformationAboutDirectoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DirectoryCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetInformationAboutDirectoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DirectoryCall': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectoryCall,
                    request_deserializer=directorselection__pb2.Request.FromString,
                    response_serializer=directorselection__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'directorselection.GetInformationAboutDirectory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetInformationAboutDirectory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DirectoryCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/directorselection.GetInformationAboutDirectory/DirectoryCall',
            directorselection__pb2.Request.SerializeToString,
            directorselection__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
